services:
  mongo-db:
    image: docker.io/mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: docker.io/mongo-express:latest
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo-db
    depends_on:
      - mongo-db

  backend:
    image: ourstory/webapp
    build:
      context: .
    ports:
      - 8080:8080
    links:
      - mongo-db
    depends_on:
      - mongo-db

#  frontend:
#    image: ourstory/frontend
#    build:
#      context: ./src/frontend
##      dockerfile: ./src/frontend/Dockerfile
#    ports:
#      - 8081:8081
#    depends_on:
#      - backend
#    links:
#      - backend